class Strategy:
    name: str
    async def on_start(self, ctx):
        ...
    async def on_quote(self, quote):
        ...
    async def on_bar(self, bar):
        ...
    async def on_fill(self, fill):
        ...
    async def on_stop(self):
        ...
