# Example GitHub Actions CI/CD pipeline
name: CI/CD
on:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - name: Install dependencies
        run: |
          pip install -r api/requirements.txt
          pip install pytest
      - name: Run tests
        run: pytest core/test_tradelogger.py
      - name: Build Docker image
        run: docker build -t infinityai-backend ./api
      - name: Push Docker image
        run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
      - name: Deploy to Azure
        run: az containerapp update --name infinityai-backend-app --resource-group InfinityAI --image infinityai-backend
