name: DISABLED - Vercel Frontend Deploy

on:
  workflow_dispatch:

jobs:
  disabled:
    runs-on: ubuntu-latest
    steps:
      - name: This workflow is deprecated
        run: echo "Vercel deployment is disabled. Use Azure Static Web Apps instead."
